[2024-04-12T00:16:17.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T00:16:17.520+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tutorial_dag.transformar_dados_em_dataframe scheduled__2024-04-11T22:30:00+00:00 [queued]>
[2024-04-12T00:16:17.532+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tutorial_dag.transformar_dados_em_dataframe scheduled__2024-04-11T22:30:00+00:00 [queued]>
[2024-04-12T00:16:17.533+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T00:16:17.823+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transformar_dados_em_dataframe> on 2024-04-11 22:30:00+00:00
[2024-04-12T00:16:17.852+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=753) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-12T00:16:17.851+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tutorial_dag', 'transformar_dados_em_dataframe', 'scheduled__2024-04-11T22:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/tutorial_dag.py', '--cfg-path', '/tmp/tmpu2luq2_l']
[2024-04-12T00:16:17.854+0000] {standard_task_runner.py:63} INFO - Started process 755 to run task
[2024-04-12T00:16:17.854+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transformar_dados_em_dataframe
[2024-04-12T00:16:17.939+0000] {task_command.py:426} INFO - Running <TaskInstance: tutorial_dag.transformar_dados_em_dataframe scheduled__2024-04-11T22:30:00+00:00 [running]> on host ae99acc4965a
[2024-04-12T00:16:18.118+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tutorial_dag' AIRFLOW_CTX_TASK_ID='transformar_dados_em_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T22:30:00+00:00'
[2024-04-12T00:16:18.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T00:16:18.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T00:16:18.154+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tutorial_dag.py", line 24, in transformar_dados_em_dataframe
    df = pd.DataFrame(json.loads(data))
                      ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
[2024-04-12T00:16:18.175+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=tutorial_dag, task_id=transformar_dados_em_dataframe, execution_date=20240411T223000, start_date=20240412T001617, end_date=20240412T001618
[2024-04-12T00:16:18.188+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transformar_dados_em_dataframe (the JSON object must be str, bytes or bytearray, not list; 755)
[2024-04-12T00:16:18.234+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T00:16:18.251+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T00:16:18.253+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
