[2024-04-12T00:42:09.477+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: tutorial_dag.verifica_quantidade_minima_valida scheduled__2024-04-11T23:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
